name: 'Smart Action Wizard'
description: 'Creates a new Smart GitHub Action based on user input'
inputs:
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.0.3'
  api-key:
    description: 'API key for PR Pilot'
    required: true
  trigger:
    description: 'Event trigger for the new GitHub Action'
    required: true
  task-description:
    description: 'Description of the task for the new GitHub Action'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/generate-new-action.py
      shell: bash
      env:
        TRIGGER: ${{ inputs.trigger }}
        PR_PILOT_API_KEY: ${{ inputs.api-key }}
        TASK_DESCRIPTION: ${{ inputs.task-description }}
