name: 'Plan and Execute'
description: 'Plans and executes tasks based on a given description and expected result'
inputs:
  task-description:
    description: 'The description of the task to plan'
    required: true
  expected-result:
    description: 'The expected result of the execution phase'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==1.2.0
      shell: bash
    - name: Plan Task
      run: python ${{ github.action_path }}/plan.py
      shell: bash
      env:
        TASK_DESCRIPTION: ${{ inputs.task-description }}
        EXPECTED_RESULT: ${{ inputs.expected-result }}
    - name: Execute Task
      run: python ${{ github.action_path }}/execute.py
      shell: bash
      env:
        PLAN: ${{ steps.plan.outputs.plan }}