name: 'Respond to Github Issue'
description: 'Reads the issue based on issue number, potentially takes action based on issue content, and adds a comment to the issue with a response'
inputs:
  issue-number:
    description: 'Number of the Github issue to respond to'
    required: true
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.3.0'
  api-key:
    description: 'API key for PR Pilot'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/respond-to-issue.py
      shell: bash
      env:
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        PR_PILOT_API_KEY: ${{ inputs.api-key }}
