name: 'Commit Monitor'
description: 'Monitors every commit and allows you to trigger tasks in commit messages'
inputs:
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.0.3'
  api-key:
    description: 'API key for PR Pilot'
    required: true
  trigger-keyword:
    description: 'Keyword to trigger task creation'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/commit-monitor.py
      shell: bash
      env:
        PR_PILOT_API_KEY: ${{ inputs.api-key }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
