name: 'Quick Task'
description: 'Creates a new PR Pilot task based on a task description provided in the action inputs'
inputs:
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.0.3'
  api-key:
    description: 'API key for PR Pilot'
    required: true
  task-description:
    description: 'The description of the task to create'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/quick-task.py
      shell: bash
      env:
        PR_PILOT_API_KEY: ${{ inputs.api-key }}
        TASK_DESCRIPTION: ${{ inputs.task-description }}