name: 'Replicator'
description: 'Take something existing and replicate it with different characteristics'
inputs:
  template:
    description: 'Path to the template file or code snippet to replicate'
    required: true
  characteristics:
    description: 'Characteristics of the result, described in natural language'
    required: true
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.3.2'
  api-key:
    description: 'API key for PR Pilot'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/replicator.py
      shell: bash
      env:
        TEMPLATE: ${{ inputs.template }}
        CHARACTERISTICS: ${{ inputs.characteristics }}
        PR_PILOT_API_KEY: ${{ inputs.api-key }}