name: 'PR Creation Handler'
description: 'Let the agent react to a new PR creation event and handle it according to your instructions'
inputs:
  pr-number:
    description: 'Number of the Github PR to handle'
    required: true
  agent-instructions:
    description: 'Instructions for how to handle the PR'
    required: true
    default: |
      - Review the PR for any obvious issues
      - Assign appropriate labels if it doesn't have any
      - Check for security concerns
      - Comment on the PR if you find anything. Otherwise say 'Looks good to me'
  sdk-version:
    description: 'PR Pilot SDK version to use'
    required: false
    default: '1.3.0'
  api-key:
    description: 'API key for PR Pilot'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pr-pilot==${{ inputs.sdk-version }}
      shell: bash
    - name: Run script
      run: python  ${{ github.action_path }}/pr-creation-handler.py
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        PR_PILOT_API_KEY: ${{ inputs.api-key }}
        AGENT_INSTRUCTIONS: ${{ inputs.agent-instructions }}