name: Smart Action Wizard
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'When should the new action be triggered?'
        required: true
        default: 'whenever a new issue is opened'
      task_description:
        description: 'What should PR Pilot do when the action is triggered?'
        required: true
        default: 'Comment on the issue with a helpful message'

jobs:
  create-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate New Smart Action
        uses: PR-Pilot-AI/smart-actions/action-wizard@v1
        with:
          trigger: ${{ github.event.inputs.trigger }}
          task_description: ${{ github.event.inputs.task_description }}
