name: Workflow Wizard

on:
  # A workflow that is triggered manually
  workflow_dispatch:
    inputs:
      workflow-name:
        description: 'Name of the new workflow'
        required: true
      trigger:
        description: 'Is this a manual workflow or should it run on a specific event?'
        required: true
      workflow-inputs:
        description: 'Does this require any inputs? If so, what are they?'
        required: false
      agent-instructions:
        description: 'What should the agent do?'
        required: true

jobs:
  generate-new-ai-workflow:
    runs-on: ubuntu-latest
    outputs:
      task-url: ${{ steps.generate-new-ai-workflow.outputs.task-url }}
    steps:
      - name: Generate new AI Workflow
        id: generate-new-ai-workflow
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            Your task is to generate a new Github workflow.
            The workflow's purpose is to automate something in the Github repository by using an AI agent 
            that can understand and execute the instructions provided in the workflow file.
            
            The workflow should be triggered in the following way:
            ```
            ${{ github.event.inputs.trigger }}
            ```
            
            It should be named `${{ github.event.inputs.workflow-name }}`
            
            The user has provided agent instructions in their own words:
            ```
            ${{ github.event.inputs.agent-instructions }}
            ```
            
            The user has also specified any inputs required for the workflow:
            ```
            ${{ github.event.inputs.workflow-inputs }}
            ```
            
            These instructions need to be turned into a step-by-step guide for the AI agent to follow.
            Make sure the step-by-step instructions are clear and concise and only contain instructions that 
            the AI agent is capable of executing:
            - Accessing and manipulating the file system
            - Reading, editing and creating Github issues
            - Searching the internet for information
            
            The workflow file must fulfill the following criteria:
            - Name of the workflow starts with emoji
            - Has only one job with one step that uses `PR-Pilot-AI/smart-actions/quick-task@v1`
            - The step should have the following inputs:
              - `api-key` (similar to reference workflow)
              - `agent-instructions` (Step-by-step instructions for the AI agent)
            - Workflow has inputs according to the user's instructions
            - Workflow is triggered according to the user's instructions
            
            
            Do the following:
            1. Read `.github/workflows/workflow_wizard.yaml` as reference to understand the desired structure of the workflow file.
            2. Turn the free-text instructions provided by the user into actionable step-by-step instructions for the AI agent.
            3. Generate the new Github workflow file and make sure the title starts with an emoji
            
